name: Build

on:
  push:
    branches: [ master, preview ]
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'
env:
    BuildProject: '.\Configuration.sln'

jobs:

  build:
    name: Build Packages
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build ${{ env.BuildProject }} -c Release

      # - name: Publish NuGets
      #   if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/preview' }}
      #   run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate