name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: [ master, dev, preview ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:

  build:
    name: Build Packages
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Add .NET 6 Android Workload
        run: dotnet workload install android

      - name: Add .NET 6 iOS Workload
        run: dotnet workload install ios

      - name: Add .NET 6 MacCatalyst Workload
        run: dotnet workload install maccatalyst

      - name: Build
        run: msbuild Build.slnf /restore -m -property:Configuration=Release

      - name: Publish NuGets
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/preview' }}
        run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate

      #- name: Create Release
      #  if: ${{ github.ref == 'refs/heads/master' }}
      #  uses: ncipollo/release-action@v1
      #  with:
      #      artifacts: "**/*.nupkg"
      #      bodyFile: "CHANGELOG.md"
      #      token: ${{ secrets.GITHUB_TOKEN }}